[build]
  base = "mallas-mys"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"

# Redirects SPA (Vue Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
